version: "3.9"

x-services-volume:
  &services-volume
  type: bind
  source: ./static
  target: /static

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: "redis:6.2-alpine"

  web:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./static:/static

  nginx:
    ports:
      - "80:80"
    depends_on:
      - web
    image: "nginx:alpine"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
