version: "3.9"
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: "redis:6.2-alpine"

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
